import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import React from 'react';
import Link from 'next/link';
import { signIn, signOut , useSession } from 'next-auth/client';

export default function Home() {

  const [session , loading ] = useSession(); 

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!session && (
          <>
            Not signed in <br />
            <button onClick={signIn}> Sign in </button>
          </>
        )}
        {session && (
          <>
          Signed in as { session.user.email} <br />
          <div> You now have access to  our secrets</div><br />
          <button>
            <Link href='/secret'>Access Page</Link>
          </button>
          <button onClick={signOut} > Sign Out</button>
          </>
        )

        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
